### ISSUE TITLE
Disable content attributes

### ISSUE THREAD

**Issue by jonathanKingston** [neftaly/npm-sri-toolbox#7]
As the spec doesn't currently mention using content type prefixes like this:
```
type:application/javascript sha-256...
```

I would suggest turning off this for now, whih also removes the chrome console issues of srihash.org

**Comment by jonathanKingston** [comment]
Also can we bump the version of this package when this goes live?

**Comment by neftaly** [comment]
Just FYI, if you add an extra line such as "Closes #7" to the commit message, it will auto-reference-and-close the relevant issue.

**Comment by jonathanKingston** [comment]
@neftaly yup I forgot to add this. Thanks again
